// Accordion.jsx
import React, { useState } from 'react';
import './Acco.css'; // ✅ Adjust this to match your actual file name
import open from '../../open.svg';

const AccordionItem = ({ question, answer }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className='mju'>
    <div className={`accordion-item3 ${isOpen ? 'open' : ''}`}>
      <div className="accordion-header3" onClick={() => setIsOpen(!isOpen)}>
        <span className="accordion-question">{question}</span>
       <span className="accordion-arrow">
  <img
    src={open}
    className={`accordion-icon ${isOpen ? 'rotate-up' : 'rotate-down'}`}
    alt="arrow"
  />
</span>

      </div>
      {isOpen && <div className="accordion-answer">{answer}</div>}
    </div>
    </div>
  );
};

const Accordion = () => {
  const faqs = [
    {
      question: 'Which art styles does Artguru provide?',
      answer:
        "Artguru image to AI art generator offers over 10 art styles, including line anime, drawing, watercolor, oil painting, cartoon, modern digital art, cyberpunk, and more. The collection continues to grow and update regularly.",
    },
    {
      question: 'What types of photos can I use with the Artguru AI art generator from photo?',
      answer: 'You can use various types of photos, including selfies, portraits, and even sketches. It is designed to enhance and transform different types of images into unique AI art styles.',
    },
     {
      question: 'How long does it take to generate AI art from photo with Artguru?',
      answer: 'The generation process is quick and efficient. Within seconds, you can transform your photos into unique AI art styles, allowing you to instantly see the remarkable results.',
    },
    {
      question: 'Can I safely upload my own photo?',
      answer: 'Rest assured, you can safely upload your photos to Artguru AI image generator. Your privacy is a top priority, and all uploaded photos are promptly deleted after AI image generation.',
    },
    {
      question: 'What kind of files will I receive?',
      answer: 'The image-to-image files generated by Artguru s AI art creator are delivered as PNG images with a resolution of 3k.',
    },

  ];

  return (
    <>
    <div className="accordion-container3">
      <h1 className="accordion-title3">FAQs about Artguru Image to AI Art Generator</h1>
      {faqs.map((faq, idx) => (
        <AccordionItem key={idx} {...faq} />
      ))}
    </div>

    <div>
  

    </div>

    

    </>
  );
};

export default Accordion;
